# Generated by Django 5.1.2 on 2024-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Papelaria', 'Papelaria'), ('Eletronico', 'Eletronico'), ('Alimento', 'Alimento')], default='Papelaria', max_length=20, null=True)),
                ('quantiity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
