# Generated by Django 5.1.2 on 2024-11-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiity',
            new_name='quantity',
        ),
    ]
